### PR TITLE
Update default_data.json add Intel contributors

### PR DESCRIPTION
**Pull request by mgkwill**

### CODE REVIEW

**Comment by dave-tucker** [comment]
According to the tests, LDAP ID's shouldn't have uppercase letters.
Also note that "List of users should be ordered by ldap id" which will need to be fixed before this passes CI

**Comment by tnadeau** [comment]
I agree. we suggest that you get the CI to pass before we merge.

**Comment by mgkwill** [comment]
All,

Last time we tried this, I confirmed that the users in question LDAP names
were case sensative and required upper case to log in. Do we still want
them in here lower case?

We can definately sort by LDAP ID but this is a pain :(

Thanks,
Marcus

**Comment by tnadeau** [comment]
Give me a few days to sort out testing this with the LF back-end to see if this actually works or not.  At the present time the tests are unit tests that are run outside

**Comment by mgkwill** [comment]
I resorted by alphabetical ldap and made all ldap names lowercase. I still think the lowercase names are likely to cause problems because login is case sensitive.

**Comment by mgkwill** [comment]
Hey Guys,

Is it possible to merge this?

 I'm still concerned about LDAP names with uppercase, but am willing to
work on that in the future if the lowercase names do not work. In the
meantime I'd like the rest of users to be reported accurately in
spectrometer.

https://github.com/dave-tucker/spectrometer/pull/19

Thanks,
Marcus

**Comment by mgkwill** [comment]
Hello,

Bumping this, as hoping to get this merged.

Thanks,
Marcus

**Comment by mgkwill** [comment]
I wonder, is spectrometer actively maintained anymore?

**Comment by tnadeau** [comment]
I wouldn’t say “actively” but more like “part time” *)

	—Tom

**Comment by tnadeau** [comment]
BTW Marcus is helping us with Spectrometer this summer as an ODL intern.

	—Tom

**Comment by mgkwill** [comment]
Tom,

Is there any reason not to merge this patch?

I talked to Jamo at the summit and he seemed to be interested in fixing spectrometer now. What is the plan for Marcus' (ODL Intern) work on Spectrometer?

Thanks,
Marcus

**Comment by tnadeau** [comment]
Sorry for the delay. Since you did what Tucker asked, we should merge this.

**Comment by mgkwill** [comment]
Awesome. Thanks.

**Comment by tnadeau** [comment]
I am not sure what happened, but apparently the merge broke the build…  That is odd as it previously passed.

**Comment by mgkwill** [comment]
I'm not sure what is happening either, it is passing now...

**Comment by mgkwill** [comment]
It seems to be failing on "ImportError: No module named oslo.config" before it ever gets to real tests.

**Comment by tnadeau** [comment]
I saw that.   Its odd.  I’ve seen other failures like this in the past that are temporal because some package did not fetch for some reason.  This is why I am looking at a major rewrite of all of this stuff from scratch...

	—Tom

**Pull request merged**
